<a href="https://colab.research.google.com/github/imran-ANU/labour_market/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving UCI_Credit_Card1.csv to UCI_Credit_Card1.csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['UCI_Credit_Card1.csv']))

In [ ]:
df.head(5)

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default.payment.next.month
0   1    20000.0    2  ...       0.0       0.0                           1
1   2   120000.0    2  ...       0.0    2000.0                           1
2   3    90000.0    2  ...    1000.0    5000.0                           0
3   4    50000.0    2  ...    1069.0    1000.0                           0
4   5    50000.0    1  ...     689.0     679.0                           0

[5 rows x 25 columns]

In [ ]:
df.shape

(30000, 25)

In [ ]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           2
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [ ]:
df.isnull().any()

ID                            False
LIMIT_BAL                     False
SEX                           False
EDUCATION                     False
MARRIAGE                      False
AGE                            True
PAY_0                         False
PAY_2                         False
PAY_3                         False
PAY_4                         False
PAY_5                         False
PAY_6                         False
BILL_AMT1                     False
BILL_AMT2                     False
BILL_AMT3                     False
BILL_AMT4                     False
BILL_AMT5                     False
BILL_AMT6                     False
PAY_AMT1                      False
PAY_AMT2                      False
PAY_AMT3                      False
PAY_AMT4                      False
PAY_AMT5                      False
PAY_AMT6                      False
default.payment.next.month    False
dtype: bool

In [ ]:
fill = df.AGE.mean()

In [ ]:
fill

35.48549903326889

In [ ]:
df.AGE = df.AGE.fillna(fill)

In [ ]:
df.AGE.isnull().sum()

0

In [ ]:
df.AGE.head(5)

0    24.000000
1    26.000000
2    35.485499
3    35.485499
4    57.000000
Name: AGE, dtype: float64

In [ ]:
x = df.drop(['default.payment.next.month'],axis=1)

In [ ]:
x.head(5)

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
0   1    20000.0    2          2  ...       0.0       0.0       0.0       0.0
1   2   120000.0    2          2  ...    1000.0    1000.0       0.0    2000.0
2   3    90000.0    2          2  ...    1000.0    1000.0    1000.0    5000.0
3   4    50000.0    2          2  ...    1200.0    1100.0    1069.0    1000.0
4   5    50000.0    1          2  ...   10000.0    9000.0     689.0     679.0

[5 rows x 24 columns]

In [ ]:
x.shape

(30000, 24)

In [ ]:
y = df['default.payment.next.month']

In [ ]:
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default.payment.next.month, Length: 30000, dtype: int64

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20,random_state=1)

In [ ]:
ytest

10747    0
12573    1
29676    0
8856     1
21098    0
        ..
26329    0
29693    0
16605    0
19704    0
12785    0
Name: default.payment.next.month, Length: 6000, dtype: int64

In [ ]:
model = SVC()

In [ ]:
model.fit(xtrain,ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
model.predict(xtest)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
model.score(xtest,ytest)

0.7771666666666667

In [ ]:
model_RF = RandomForestClassifier()

In [ ]:
model_RF.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
model_RF.predict(xtest)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
model_RF.score(xtest,ytest)

0.8165

In [ ]:
model_DT = DecisionTreeClassifier()

In [ ]:
model_DT.fit(xtrain,ytrain)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model_DT.predict(xtest)

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
model_DT.score(xtest,ytest)

0.7168333333333333

In [ ]:
model_GNB = G